### ISSUE TITLE
performance issue when opening model.star file

### ISSUE THREAD

**Issue by inter1965** [alisterburt/starfile#3]
When coping with a star file contains thousands of sub data blocks(.e.g. 3D classification's model file), is it possible to use a mmap or stringio buffer object to feed pandas.read_csv's argument in _read_loop_data to increase the performance? Otherwise it might take hours to read a model star file.
Furthermore, add an option to read just first several blocks would be a nice addition to speed up specific case.
Cheers.

**Comment by alisterburt** [comment]
This sounds like a great idea, would you mind sending me a large RELION model star file for testing? 

I will probably try use stringio because I have used these before but if you have experience with mmap and would like to have a go it would be good to compare both!

The idea about an option for just reading the first few blocks is a good one and should work with the way things are set up - I’ll look into it over the next week or so.

Cheers,

Alister

**Comment by inter1965** [comment]
Wow, the mail system complained about the size of the original file. Hope
the zipped version works.
Best,
X

**Comment by inter1965** [comment]
Here's one example, hope it could help.
[model.zip](https://github.com/alisterburt/starfile/files/5371573/model.zip)

**Comment by alisterburt** [comment]
thanks!

I have a solution which reads files much faster now but it's failing a
couple of tests so I need to debug a little more - hopefully I'll have it
up very soon.

On my machine the new parser reads a 1 million line file split into 1000
blocks of 1000x10 tables in ~10s - I've also added the option for only
reading the first N blocks in case you want to skip things as you suggested

**Comment by alisterburt** [comment]
I got myself quite lost in bugs trying to finish up the optimisations so I reverted to the last working state which was already faster and pushed it to pypi (v0.2.3) - will go over it properly when I have a little more time

**Comment by alisterburt** [comment]
refactored, clean and working nicely now - hopefully this makes things faster for you. 
Please update to v0.3.1
