### ISSUE TITLE
how to read two-block starfile and get access to second block specifically

### ISSUE THREAD

**Issue by bingwang14** [alisterburt/starfile#30]
Hi Alister,

I previously used starfile open attribute (starfile.open) to open and edit .star file, but I just realized this attribute has been deleted. Then I tried to use  starfile.read instead, but seemly this function doesn't allow me to get access to the second block. It looks like the function only read a single-block starfile.  So how to get access to the second block specifically?  I pasted the following scripts, which doesn't work anymore. Could you help me to revise it? Thank you very much.

df = starfile.open('particles.star')
b = int((len(df[1])) / 2)  # how to specifically get access to the second block, as df[1] doesn't work here?
a = int(b / 2)
df1 = df[1].iloc[:a]
df2 = df[1].iloc[a:b]
starfile.new(df1, 'particles_s1.star', float_format='%.6f')  
starfile.new(df2, 'particles_s2.star', float_format='%.6f')

Best,
Bing

**Comment by alisterburt** [comment]
Hi @bingwang14 ! Sorry to have borked your script, thanks for opening an issue.

First, the reason for this change is that 'open' typically gives you access to a file still on disk, 'read' reads the contents of a file into memory - starfile only does the latter so read is more appropriate.

It has been quite a long time since starfile returned a list - this appears to be what you expect based on your numerical indexing. Instead, if multiple data blocks are present starfile will return a dictionary of dataframes - with a dictionary you use keys to access specific values directly

e.g.
star = starfile.read('particles.star')
optics_df = star['optics']
particle_df = star['particles']

You can see the keys of a dictionary with

print(star.keys())

Hope that helps?
